language: go
arch:
  - amd64
  - ppc64le
go:
  - 1.12
  - 1.13
  - 1.14
before_install:
  - go get -t -v ./...

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
